#!/bin/bash
# Run the Joseki RDF server 

-Dorg.mortbay.jetty.Request.maxFormContentSize=500000

[ "$JOSEKIROOT" = "" ] && { echo "JOSEKIROOT unset" 1>&2 ; exit 1 ; }

"$JOSEKIROOT/bin/rdfserver" "$@"
