#!/bin/bash

# Before running this ....
# Ensure the two services "update/service" and "sparql/read" exists 
# Named graph update only works on a mutable dataset (so not an ad-hoc in-memory one)

UPDATE="${1:-update.ru}"

export  http_proxy=
echo "=== Update"
wget -q -O - --post-data="request=$(cat $UPDATE)"  'http://localhost:2020/update/service'
echo
echo "=== Default graph"
wget -q -O - 'http://localhost:2020/sparql?query=SELECT * { ?s ?p ?o}&output=text'
echo
echo "=== Named graphs"
wget -q -O - 'http://localhost:2020/sparql?query=SELECT * { GRAPH ?g { ?s ?p ?o}}&output=text'
