/* CVS $Id: JosekiMap.java,v 1.1 2005-06-23 10:16:16 andy_seaborne Exp $ */
 
package dev;
import com.hp.hpl.jena.rdf.model.*;

// Experimental - encoding a map in RDF

/**
 * Vocabulary definitions from file:vocabularies/map.n3 
 * @author Auto-generated by schemagen on 05 Feb 2004 14:23 
 */
public class JosekiMap {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabalary as a string ({@value})</p> */
    public static final String NS = "http://joseki.org/2004/02/map#";
    
    /** <p>The namespace of the vocabalary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabalary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property key = m_model.createProperty( "http://joseki.org/2004/02/map#key" );
    
    public static final Property entry = m_model.createProperty( "http://joseki.org/2004/02/map#entry" );
    
    public static final Property value = m_model.createProperty( "http://joseki.org/2004/02/map#value" );
    
    public static final Resource MapValue = m_model.createResource( "http://joseki.org/2004/02/map#MapValue" );
    
    public static final Resource MapKey = m_model.createResource( "http://joseki.org/2004/02/map#MapKey" );
    
    public static final Resource Map = m_model.createResource( "http://joseki.org/2004/02/map#Map" );
    
    public static final Resource MapEntry = m_model.createResource( "http://joseki.org/2004/02/map#MapEntry" );
    
}
