#!/bin/bash

# Joseki example: query a remote model.
MODEL="http://localhost:2020/joseki-example"

OBJ="http://example.org/book/book1" 

# Fetch

java -cp "$(./joseki_path)" joseki.rdffetch --model "$MODEL" --resource "$OBJ"
