#!/bin/bash

# Joseki example: get a published RDF model
# Fetch book3 and related information

export http_proxy=

MODEL="http://localhost:2020/joseki-example"

# Need to %-encode if it uses, say, frag ids
OBJ="http://example.org/book/book3"

# Construct the request
URI="${MODEL}?lang=fetch&r=${OBJ}"

FORMAT="application/n3"

wget -q -O - --header "Accept: $FORMAT" "$URI"

# Note it returns the vCArd as well because this is a bNode.
