#!/bin/bash 

JOSEKIROOT=".."
HERE="$PWD"
# Make absolute
cd "$JOSEKIROOT" ; JOSEKIROOT=$PWD ; cd "$HERE"

first=1
[ "$CP" != "" ] && first=0 

for jar in $JOSEKIROOT/lib/*.jar
do
  #echo "Path: $jar"
  # Order matters here
  [ "$first" == 0 ] && CP="$CP;"
  [ "$first" == 1 ] && first=0
  CP="${CP}$jar"
done

echo $CP
