#!/bin/bash

# XML parser
CP="$(alljars ../lib)"
CP="$CP;$(alljars ../lib2)"
CP="../classes;$CP"

LOGCONFIG=${LOGCONFIG:-file:log4j.properties}
LOG="-Dlog4j.configuration=${LOGCONFIG}"

# echo $CP
java -cp "$CP" $LOG org.apache.axis.transport.http.SimpleAxisServer -p 2525
