#!/bin/bash

# XML parser
CP="$(alljars ../lib)"
CP="$CP;$(alljars ../lib2)"
CP="../classes;$CP"

## if [ $# == 0 ]
## then
##     args="-p 2525"
## else
##     args="$@"
##     fi

java -cp "$CP" org.apache.axis.client.AdminClient -p 2525 "$@"
