<?xml version="1.0"?>
<wsd1:definitions
     xmlns:wsd1="http://schemas.xmlsoap.org/wsdl/"
     xmlns:wsd2="http://www.w3.org/2004/08/wsdl" 
     xmlns:whttp="http://www.w3.org/2004/08/wsdl/http"
     xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
     xmlns:st="http://www.w3.org/2001/sw/DataAccess/sparql-protocol-types"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xs="http://www.w3.org/2001/XMLSchema"
     xmlns:xrf="http://www.w3.org/2001/sw/DataAccess/rf1/result"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     schemaLocation="http://www.w3.org/2004/08/wsdl http://www.w3.org/2004/08/wsdl" 
     targetNamespace="http://www.w3.org/2005/01/sparql-protocol-query"

     st:kludge="kludge" rdf:kludge="kludge" whttp:kludge="kludge" xs:kludge="kludge" xrf:kludge="kludge" xsi:kludge="kludge">

  <wsd1:portType name="SparqlQuery">
    <wsd1:operation name="query">
      <wsd1:input message="st:query"/>
      <wsd1:output message="st:query-result"/>
    </wsd1:operation>
  </wsd1:portType>
  <wsd1:types>
    <xs:import namespace="http://www.w3.org/2001/sw/DataAccess/rf1/result"/>

    <xs:import namespace="http://www.w3.org/2001/sw/DataAccess/sparql-protocol-types"/>
  </wsd1:types>
  <wsd1:binding name="httpSparqlQueryBinding" type="SparqlQuery">
    <http:binding verb="GET"/>
    <wsd1:operation name="query">
      <wsd1:input>
	<http:urlEncoded/>
      </wsd1:input>
    </wsd1:operation>

  </wsd1:binding>
  <wsd1:service name="httpSparqlQueryBinding_testSvc">
    <wsd1:port name="httpSparqlQueryBinding_testPort" binding="httpSparqlQueryBinding"/>
  </wsd1:service>
  <wsd1:binding name="soapSparqlQueryBinding" type="SparqlQuery"/>
  <wsd1:service name="soapSparqlQueryBinding_testSvc">
    <wsd1:port name="soapSparqlQueryBinding_testPort" binding="soapSparqlQueryBinding"/>
  </wsd1:service>
</wsd1:definitions>
