<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions
     targetNamespace="http://www.w3.org/2005/01/sparql-protocol-query"
     xmlns:tns="http://www.w3.org/2005/01/sparql-protocol-query"

     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"

     xmlns:st="http://www.w3.org/2001/sw/DataAccess/sparql-protocol-types"
     xmlns:vbr="http://www.w3.org/2001/sw/DataAccess/rf1/result2"

     xmlns:wsd2="http://www.w3.org/2004/08/wsdl" 
     xmlns:whttp="http://www.w3.org/2004/08/wsdl/http"
     xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"

     xmlns:xs="http://www.w3.org/2001/XMLSchema"

     xmlns:xrf="http://www.w3.org/2001/sw/DataAccess/rf1/result"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     schemaLocation="http://www.w3.org/2004/08/wsdl" 
     >


  <wsdl:import namespace="http://www.w3.org/2001/sw/DataAccess/rf1/result2"
               location="result2.xsd"/>

<!--
  <wsdl:import namespace="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
-->

  <!-- WSDL 2-ism?
  <wsdl:types>
    <xs:import namespace="http://www.w3.org/2001/sw/DataAccess/rf1/result"/>
    <xs:import namespace="http://www.w3.org/2001/sw/DataAccess/sparql-protocol-types"/>
    <xs:import namespace="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
  </wsdl:types>
  -->

  <wsdl:import namespace="http://www.w3.org/2001/sw/DataAccess/sparql-protocol-types"
               location="sparql-types.xsd"/>

  <wsdl:message name="queryRequest">
    <wsdl:part name="query" element="st:query"/>
  </wsdl:message>

  <wsdl:message name="queryResponse">
    <wsdl:part name="response" element="st:query-result"/>
  </wsdl:message>

  <wsdl:portType name="QueryType">
    <wsdl:operation name="query">
      <wsdl:input message="tns:queryRequest"/>
      <wsdl:output message="tns:queryResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="QuerySoapBinding" type="tns:QueryType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="query">
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>


  <wsdl:service name="JosekiQueryService">
    <wsdl:port binding="tns:QuerySoapBinding" name="sparql-query">
      <soap:address location="http://localhost:2525/axis/services/sparql-query"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>

