#!/bin/bash
export AXIS_HOME="$SYS/axis-1_2_1"

CP="$(make_classpath $AXIS_HOME)"
CP="$CP;classes"


# Output in "org.joseki.ws1"
rm -f src/org/joseki/ws1/*.java

# WSDL to Web Service (Server)
# Args: -c --implementationClassName
#       -w --wrapArrays
# --buildFile

java $SOCKS -cp "$CP" org.apache.axis.wsdl.WSDL2Java \
	-o src -d Session -s -S true          \
        -Nhttp://www.w3.org/2005/01/sparql-protocol-query org.joseki.ws1  \
	$*

[ "$?" = "0" ] || exit $? ;