<?xml version="1.0" encoding="utf-8"?>

<!-- $Id: sparql-protocol-query-v1.wsdl,v 1.1 2007-08-28 10:16:55 andy_seaborne Exp $ -->

<description xmlns="http://www.w3.org/2005/08/wsdl"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  xmlns:whttp="http://www.w3.org/2005/08/wsdl/http"
  xmlns:st="http://www.w3.org/2005/09/sparql-protocol-types/#"
  xmlns:wsoap="http://www.w3.org/2005/08/wsdl/soap"
  xmlns:wsdlx="http://www.w3.org/2005/08/wsdl-extensions"
  xmlns:tns="http://www.w3.org/2005/08/sparql-protocol-query/#"
  targetNamespace="http://www.w3.org/2005/08/sparql-protocol-query/#">

  <documentation>
    This document describes the SPARQL Protocol for RDF as a web
    service with one interface, SparqlQuery, containing one operation,
    query; as welll as HTTP and SOAP bindings of that interface. See
    http://www.w3.org/2001/sw/DataAccess/proto-wd/ for the SPARQL
    Protocol for RDF specification.
  </documentation>

  <!-- type imports -->
  <types>
    <!-- the SPARQL XML Results Format namespace -->
    <xs:import namespace="http://www.w3.org/2005/sparql-results#"/>
    <!-- Types for SPARQL Protocol -->
    <xs:import namespace="http://www.w3.org/2005/09/sparql-protocol-types/#"/>
  </types>

  <!-- SparqlQuery -->
  <interface name="SparqlQuery" styleDefault="http://www.w3.org/2005/08/wsdl/style/iri">

    <!-- the faults -->
    <fault name="MalformedQuery" element="st:malformed-query"></fault>
    <fault name="QueryRequestRefused" element="st:query-request-refused"></fault>

    <operation name="query" pattern="http://www.w3.org/2005/08/wsdl/in-out"
	       wsldx:safe="true">

      <documentation>The operation is used to convey queries and their
      results from clients to services and back
      again..</documentation>

      <input messageLabel="In" element="st:query-request"/>
      <output messageLabel="Out" element="st:query-result"/>

      <outfault ref="tns:MalformedQuery" messageLabel="Out"/>
      <outfault ref="tns:QueryRequestRefused" messageLabel="Out"/>
    </operation>

  </interface>
 
  <!-- HTTP bindings -->
  <binding name="queryHttp" interface="tns:SparqlQuery" 
	    type="http://www.w3.org/2005/08/wsdl/http"
	    whttp:version="1.1">

    <fault name="MalformedQuery" whttp:code="400"/>
    <fault name="QueryRequestRefused" whttp:code="500"/>

    <!-- the GET binding for query operation -->
    <operation ref="tns:query" whttp:method="GET"
	       whttp:inputSerialization="application/x-www-form-urlencoded" />

    <!-- the POST binding for query operation -->
    <operation ref="tns:query" whttp:method="POST" 
	       whttp:inputSerialization="multipart/form-data" />

  </binding>

  <!-- SOAP 1.2 bindings: HTTP is underlying protocol; POST is the method. -->
  <binding name="querySoap" interface="SparqlQuery"
	    type="http://www.w3.org/2005/08/wsdl/soap"
            wsoap:version="1.2" >
	    wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP">

    <fault ref="MalformedQuery" wsoap:code="soap:Sender" />
    <fault ref="QueryRequestRefused" wsoap:code="soap:Sender" />

    <operation ref="query" wsoap:mep="http://www.w3.org/2003/05/soap/mep/request-response" />

  </binding>
</description>
