#!/bin/env perl

print "==== Example 2 - do a plain GET - list titles\n" ;

require Joseki ;
require RDF::Core::Model ;
require RDF::Core::Model::Serializer ;
require RDF::Core::Resource ;

my $DC = 'http://purl.org/dc/elements/1.1/' ;
my $dcTitle = $DC.'title' ;

my $kbURL = 'http://jena.hpl.hp.com:2020/books' ;
if ( $#ARGV != -1 )
{
    $kbURL = shift ;
    print "Data source = $kbURL\n" ;
}

my $model = Joseki->getModel($kbURL) ;
die "Failed to get the model from URL $kbURL" if ! defined $model ;


my $dcTitleR = new RDF::Core::Resource($dcTitle) ;
my $sIter = $model->getStmts(undef, $dcTitleR, undef) ;

my $statement = $sIter->getFirst; 
for(; defined $statement ; $statement = $sIter->getNext )
{
    print $statement->getSubject->getLabel ;
    print " ==> " ;
    print $statement->getObject->getLabel."\n";
}
$sIter->close;
